server:
  port: 8080

datasource:
  host: 192.168.152.101 #mysql 的ip
  port: 3306  # mysql 的端口号
  username: root  # mysql 的root
  password: 123   # mysql 的pwd
  database_name: zjx_reception # mysql 数据库名称

file:
  save:
    path: C:\Users\27416\Desktop\filepath   # 文件保存地址
